### ISSUE TITLE
auth no longer working

### ISSUE THREAD

**Issue by bchristian14** [mlowijs/tesla_api#37] opened 2021-01-30 17:45 UTC
Tesla has deprecated the /oauth/token endpoint in favor of using auth.tesla.com. It's been about 45 days since I initially started using this, so I suspect my original token has expired, and no longer able to get a new oauth token.

This appears to be discussed here https://tesla-api.timdorr.com/api-basics/authentication

**Comment by Dreamsorcerer** [comment] 2021-01-30 17:46
Duplicate of #31

**Closed as completed by Dreamsorcerer** 2021-01-30 17:46 UTC
